services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: n_store
      POSTGRES_HOST_AUTH_METHOD: trust